version: "3"
services:
  bot:
    build: .
    ports:
      - "9222:9222"
    env_file: .env
    restart: on-failure
    volumes:
      - .:/home/yobot/yobot
    networks:
      - bot_net

  miraiok:
    image: lqbing/miraiok
    restart: always
    volumes:
      - ./config.txt:/workdir/config.txt
      - ./setting.yml:/workdir/plugins/CQHTTPMirai/setting.yml
      - ./device.json:/workdir/device.json
      - ./log:/workdir/log
    networks:
      - bot_net
    stdin_open: true
    tty: true

networks:
  bot_net:
    driver: bridge
